# Generated by Django 4.0.3 on 2022-04-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxygenCylinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
