# Generated by Django 4.0.3 on 2022-04-03 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=255)),
                ('hospital_address', models.TextField()),
                ('hospital_type', models.CharField(choices=[('PRIVATE', 'PRIVATE'), ('GOVERNMENT', 'GOVERNMENT'), ('SEMI-GOVERNMENT', 'SEMI-GOVERNMENT')], default='PRIVATE', max_length=50)),
                ('hospital_code', models.CharField(max_length=100)),
                ('hospital_website', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalPhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticationAPI.hospitaluser')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_email', models.EmailField(max_length=254)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticationAPI.hospitaluser')),
            ],
        ),
    ]
